---
title: "big_5_rcode_GB.Men"
author: "Xinyi"
date: "15/03/2022"
output:
  html_document: default
  word_document: default
  pdf_document: default
---
# update sgnmodeltext and L_zeros
# use 1101 function -weights bic 
#sum(L_tmp) -> sum(L_tmp!=0)
# change1110 use cl1110_Lp_fun rather than cl1110_o_r_f
# added return and chart maker
# 1121 change the irls bug
```{r setup, include=FALSE}
options(digits=3)
knitr::opts_chunk$set(fig.width=20)
```

## R Markdown


```{r,data}
library(arm)
library(ggplot2)
#path 
setwd(paste0(path,'/Rdata'))
Big5.dat = read.csv('data.csv',header=TRUE, stringsAsFactors = T,sep = '\t')
setwd(path)
source('cl1121_Lp_fun.R')#irls function
# British men, Popu
Big5.GB = subset(Big5.dat,country=="GB")
Big5.GB.M = subset(Big5.GB,gender==1)  
dat = Big5.GB.M
n_row = 50
n_col = 5
N = nrow(dat)
print(N)
S = cov(dat[8:57],dat[8:57])
var_nam = paste0('x',1:n_row)
rownames(S)[1:n_row]  = colnames(S)[1:n_row] = var_nam

## answer key for BIG5
L_big5 = matrix(0,50,5)
L_big5[1:10,1]=c(1,-1,1,-1,1,-1,1,-1,1,-1)
L_big5[10+1:10,2]=c(-1,1,-1,1,-1,-1,-1,-1,-1,-1)
L_big5[20+1:10,3]=c(-1,1,-1,1,-1,1,-1,1,1,1)
L_big5[30+1:10,4]=c(1,-1,1,-1,1,-1,1,-1,1,1)
L_big5[40+1:10,5]=c(1,-1,1,-1,1,-1,1,1,1,1)
```

## Including Plots

You can also embed plots, for example:

```{r,functions}
## log-likelihood 
g <- function(Sigma,S){
  log(det(2*pi*Sigma))+sum(diag(S %*% solve(Sigma)))
}

## sub-gradient of Lambda
Subg_Lambda <- function(Q,Lambda,Phi){
  2*Q %*% Lambda %*% Phi
}

## we use Phi instead of T to parameterise the likelihood 
Subg_Phi1 <- function(Q,Lambda){
  grad_Phi <-2* t(Lambda) %*% Q %*% Lambda
  return(grad_Phi)
}

## sub-gradient of Psi
Subg_Psi <- function(Q,Psi){
  diag(Q)*exp(Psi)
}

## objective function (in vector)
fx<-function(x,n_row,n_col,L_zeros,S){
  #reconstruct Lambda,Psi,Phi from vector x
  Lnco = sum(L_zeros!=0)
  Lambda<-matrix(0,n_row,n_col)
  Lambda[which(L_zeros!=0)] = x[1:Lnco]
  Psi = x[Lnco+1:n_row]
  Phi = diag(n_col)
  Phi[lower.tri(Phi)] = x[Lnco+n_row+1:(n_col*(n_col-1)/2)]
  Phi[upper.tri(Phi)] = t(Phi)[upper.tri(Phi)]
  Sigma  = Lambda%*%Phi%*%t(Lambda)+diag(exp(Psi))
return(g(Sigma,S))}

## gradient of objective function (in vector)
grad_fx<-function(x,n_row,n_col,L_zeros,S){
  Lnco = sum(L_zeros!=0)
  Lambda = matrix(0,n_row,n_col)
  Lambda[which(L_zeros!=0)] = x[1:Lnco]
  Psi = x[Lnco+1:n_row]
  Phi = diag(n_col)
  Phi[lower.tri(Phi)] = x[Lnco+n_row+1:(n_col*(n_col-1)/2)]
  Phi[upper.tri(Phi)] = t(Phi)[upper.tri(Phi)]
  Sigma  = Lambda%*%Phi%*%t(Lambda)+diag(exp(Psi))
  Sigma_inv  = solve(Sigma)
  Q = Sigma_inv-Sigma_inv%*%S%*%Sigma_inv
  grad_Lambda =  Subg_Lambda(Q,Lambda,Phi)
  grad_Psi1 =  Subg_Psi(Q,Psi)
  grad_Phi = Subg_Phi1(Q,Lambda)
  return(c(grad_Lambda[L_zeros!=0],grad_Psi1,grad_Phi[lower.tri(grad_Phi)]))}

##solve the MLE under sign constraints,also can estimate confidence interval 
sgnrefit_optim2<-function(L_irls,L_zeros,S,N,if_se=1,Psi0=rep(0,n_row),Phi0=rep(0,n_col*(n_col-1)/2)){
  n_row = nrow(L_irls)
  n_col = ncol(L_irls)
  
  # input a vector L,Psi,B
  Lnco = sum(L_zeros!=0)
  L0 = L_irls[L_zeros!=0]
  x0 = c(L0,Psi0,Phi0)
  
  # set sign constraints, where L_zeros=2 means no constraints(used in CI calculation)
  # L_zeros>0 means positive sign, L_zeros<0 means negative sign
  lowerb = rep(-Inf,length(x0))
  lowerb[which(((L_zeros[L_zeros!=0])>0)&(L_zeros[L_zeros!=0]!=2))] = 10^(-3)
  upperb = rep(Inf,length(x0))
  upperb[which((L_zeros[L_zeros!=0])<0)] = -10^(-3)
  
  # solve the MLE by BFGS with sign constraints
  result<-optim(x0, fx, grad_fx, n_row=n_row, n_col=n_col,L_zeros=L_zeros,S=S*(N-1)/N,
                                 method = "L-BFGS-B",lower = lowerb,upper=upperb, hessian = T)
  x = result$par
  bic = N*result$value+log(N)*length(x0)
  L_up = L_low = Lambda = matrix(0,n_row,n_col)
  Lambda[which(L_zeros!=0)] = x[1:Lnco]
  
  # construct confidence interval
  se_est = sqrt(diag(solve(N*result$hessian/2))) #standard error
  L_up[which(L_zeros!=0)] = (x+1.96*se_est)[1:Lnco]
  L_low[which(L_zeros!=0)] = (x-1.96*se_est)[1:Lnco]
  return(list(bic=bic,Lambda=Lambda,Psi=x[Lnco+1:n_row],Phi=x[Lnco+n_row+1:(n_col*(n_col-1)/2)]
              ,u=L_up,l=L_low))
}

## calculation confidence interval with sign constraints row by row
CI_refit3<-function(L_irls,L_zeros,S,N,Psi0, Phi0){
  t1 = proc.time()
  CI=matrix(0,n_row,2*ncol(L_zeros))
  for ( k in 1:nrow(L_zeros)){
    L_tmp = L_zeros
    L_tmp[k,] = 2
    res = sgnrefit_optim2(L_irls,L_tmp,S,N,if_se=1,Psi0=Psi0,Phi0=Phi0)
    CI[k,]=c(res$l[k,],res$u[k,])
  }
  print((proc.time()-t1)[3])
  return(CI)
}

## permutation and sign flip of the solution towards the answer key
permfilp <- function(L_irls){
  n_col = ncol(L_irls)
  L_new0 = L_irls
  # column-swap
  for( i in 1:n_col){
  L_new0[,i] = L_irls[,which.max(colSums(abs(L_irls)[(i*10-10+1:10),]))]}
  # sign-flip
  D2 = diag(rep(5,1))
  signs = c(1,-1,-1,1,1)
  for( i in 1:n_col){
    if(L_new0[(i*10-9),i]*signs[i]<0){
      L_new0[,i] = -L_new0[,i]
      D2[i,i] = -1}
    }
  return(list(L_new0 = L_new0,D2 = D2))
}

## main function Lp rotation+BIC selection with sign constraints+
## confidence interval calculation
Lp_selCI<-function(L_vari,S,N,p,Psi_cfa,n_row=50,n_col=5,T0=diag(rep(1,n_col))){
# threshold  
c_list = c(seq(0.06,0.3,by=0.02))

#irls
irls_result = irls(p,L_vari,T=T0)
print('irls Loadings')
L_irls = permfilp(irls_result$L)$L_new0
print(round(L_irls,3))
print('irls covariance')
T_irls = irls_result$T
Phi_irls=t(T_irls)%*%T_irls
Phi0=Phi_irls[lower.tri(Phi_irls)]
Psi0=log(Psi_cfa)
print(round(Phi_irls,3))

# bic selection
bic = Inf
print('bic')
for (j in 1:length(c_list)){
  # hard-thresholding with sign constraints
  L_zeros=(abs(L_irls)>c_list[j])*sign(L_irls)
  # refit with new Q-matrix
  refit_res = sgnrefit_optim2(L_irls,L_zeros,S,N)
  bic_new = refit_res$bic
  print(paste(bic_new))
  if(bic_new < bic){
    bic = bic_new
    L_bic = refit_res$Lambda
    cov_bic = refit_res$Phi
    c = c_list[j]
    print(c_list[j])
  }
}
print('loading matrix selected by bic')
print(round(L_bic,3))
print('number of nonzeros')
print(table(L_bic!=0))
print('covariance matrix selected by bic')
print(round(cov_bic,3))

#confidence interval
CI_results = CI_refit3(L_irls,sign(L_bic),S,N,Psi0,Phi0)
print('lower bound for 95% Confidence interval')
print('upper bound for 95% Confidence interval')
print(round(CI_results,3))
# detect sign
print('elements that are rejected as zeros')
L_zeros=!((CI_results[,1:5]<0)&(CI_results[,6:10]>0))
L_zeros[which((CI_results[,1:5]<0)&(CI_results[,6:10]<0))]=-1
L_zeros[which(is.na(CI_results[,1:5]))]=Inf
L_star=L_zeros
L_star[L_zeros==0]= ' '
L_star[L_zeros!=0]= '*'
print(round(L_zeros,2))
print('number of nonzeros')
print(table(L_zeros!=0))
 if(T){
write.csv(round(Phi_irls,3),file = paste0("1110cov",p,".csv"))
write.csv(cbind(L_star,round(cbind(L_bic,L_irls,CI_results),3)),file = paste0("1110irlsL_CI",p,".csv"))}
 # add perm to L_irls
return(list(L_irls = L_irls,
      T_irls = T_irls,
      L_bic = L_bic,
      cov_bic = cov_bic,
      CI = CI_results,
      L_zeros = L_zeros,
      out=cbind(L_star,round(cbind(L_bic,L_irls,CI_results),3))))
}
```

```{r,initial value}
## initial orthogonal solution \hat{A} solved by cfa
library(lavaan)
L_tmp = matrix(1,n_row,n_col)
L_tmp[upper.tri(L_tmp)] = 0
fit  = cfa(modeltext(L_tmp),
          sample.cov=S,
          orthogonal=T,
          sample.nobs=N)
Lnco = sum(L_tmp)
L_cfa = matrix(0,n_row,n_col)
L_cfa[L_tmp!=0] = coef(fit)[1:Lnco]
Psi_cfa<-coef(fit)[Lnco+1:n_row]
# warm start for obliqur rotation-varimax rotation
L_vari = L_cfa %*% varimax(L_cfa)$rotmat
L_vari  = permfilp(L_vari)$L_new0
```



```{r,L1}
res_1 = Lp_selCI(L_vari,S,N,1,Psi_cfa)
```



```{r,tab.k1-3}
library(xtable)

L_big5 = matrix(0,50,5)
L_big5[1:10,1]=c(1,-1,1,-1,1,-1,1,-1,1,-1)
L_big5[10+1:10,2]=c(-1,1,-1,1,-1,-1,-1,-1,-1,-1)
L_big5[20+1:10,3]=c(-1,1,-1,1,-1,1,-1,1,1,1)
L_big5[30+1:10,4]=c(1,-1,1,-1,1,-1,1,-1,1,1)
L_big5[40+1:10,5]=c(1,-1,1,-1,1,-1,1,1,1,1)

make_table57 <- function(res_1, p,L_big5=L_big5){
cnames=c('E','ES','A','C','I')
res=matrix(0,100,5)
rnames=c()
for (j in 1:5){
  new_names=L_big5[1:10+j*10-10,j]
  new_names[new_names<0]<-'(-)'
  new_names[new_names>=0]<-'(+)'
  for ( i in 1:10){
  rnames=append(rnames, paste0(cnames[j],i,new_names[i]))
  rnames=append(rnames,' ')}
} 
#rownames(res) = rnames
colnames(res) = cnames
#print(res)

L_star=res_1$L_zeros
L_star[res_1$L_zeros==0]= ' '
L_star[res_1$L_zeros!=0]= '*'

#res_1$L_irls
#res_1$CI_results

for ( i in 1:50){
  for (j in 1:5){
    res[2*i-1,j]= paste0(sprintf("%6.3f",res_1$L_irls[i,j]),L_star[i,j])
    res[2*i,j]=paste0('(', sprintf("%6.3f",res_1$CI[i,j]),',', sprintf("%6.3f",res_1$CI[i,j+5]),')')
  }
}

setwd('C:/Users/dell/OneDrive - London School of Economics/Lprot/resubmission/redoexperiment1115/big51115')
write.csv(res,file = paste0("1115CI",p,".csv"))
return(cbind(rnames,res))}

table57 = make_table57(res_1, 1,L_big5)
name1 = ' Part I: Point estimates and confidence intervals constructed by L1, big-five personality test. The loadings that are significantly different from zero according to the 95% confidence intervals are indicated by asterisks.'
name2 = ' Part II: Point estimates and confidence intervals constructed by L1, big-five personality test.'
name3 = ' Part III: Point estimates and confidence intervals constructed by L1, big-five personality test.'
print(xtable(table57[1:40,],align = "ll|ccccc",label=c('empCI0.5_1'),caption=c(name1)),include.rownames=FALSE)
print(xtable(table57[41:80,],align = "ll|ccccc",label=c('empCI0.5_2'),caption=c(name2)),include.rownames=FALSE)
print(xtable(table57[81:100,],align = "ll|ccccc",label=c('empCI0.5_3'),caption=c(name3)),include.rownames=FALSE)
```


```{r,L0.5}
res_0.5 = Lp_selCI(L_vari,S,N,0.5,Psi_cfa,T0=res_1$T_irls)
```

```{r,tab.5-7}
table810 = make_table57(res_0.5, 0.5,L_big5)
name1 = ' Part I: Point estimates and confidence intervals constructed by L0.5, big-five personality test. The loadings that are significantly different from zero according to the 95% confidence intervals are indicated by asterisks.'
name2 = ' Part II: Point estimates and confidence intervals constructed by L0.5, big-five personality test.'
name3 = ' Part III: Point estimates and confidence intervals constructed by L0.5, big-five personality test.'
print(xtable(table810[1:40,],align = "ll|ccccc",label=c('empCI0.5_1'),caption=c(name1)),include.rownames=FALSE)
print(xtable(table810[41:80,],align = "ll|ccccc",label=c('empCI0.5_2'),caption=c(name2)),include.rownames=FALSE)
print(xtable(table810[81:100,],align = "ll|ccccc",label=c('empCI0.5_3'),caption=c(name3)),include.rownames=FALSE)

```


```{r,fig.width=20,fig.height=10}
library("lattice")
library('gridExtra')
visual<-function(L,name,ifnew){
colnames(L)  =  c('E','ES','A','C','O')
rownames(L)  =  paste( rep("Q",nrow(L)) , c(1:nrow(L)) , sep=" ")
return(levelplot(t(L[c(nrow(L):1),]),xlab="big 5 character", ylab='items',at=c(-1.3, seq(-1.05, 1.05, 0.1), 1.3),
          colorkey = list(tri.lower = TRUE, tri.upper = TRUE),
           main=name) )

}

#pdf(file='11_6res_test1.pdf',width=20, height = 10)
p1 = visual(L_big5,'True big5 matrix',F)
p2 = visual(L_vari,'L_varimax',T)
p3 = visual(res_0.5$L_irls,'p=0.5',T)
p4 = visual(res_0.5$L_zeros,'L_zeros0.5',T)
p5 = visual(res_1$L_irls,'p=1',T)
p6 = visual(res_1$L_zeros,'L_zeros1',F)
grid.arrange(p1,p2,p3,p4,p5,p6,nrow=1)
#dev.off()

```




Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
